export const functionButtons = [
    { text: 'Rad', value: null, order: 0 },
    { text: 'Deg', value: null, order: 1 },
    { text: 'x!', value: null, order: 2 },
    { text: 'Inv', value: null, order: 7 },
    { text: 'sin', value: null, order: 8 },
    { text: 'ln', value: null, order: 9 },
    { text: 'π', value: null, order: 14 },
    { text: 'cos', value: null, order: 15 },
    { text: 'log', value: null, order: 16 },
    { text: 'e', value: null, order: 21 },
    { text: 'tan', value: null, order: 22 },
    { text: '√', value: null, order: 23 },
    { text: 'Ans', value: null, order: 28 },
    { text: 'EXP', value: null, order: 29 },
    { text: 'x<sup>y</sup>', value: null, order: 30 },
];

export const equationButtons = [
    { style: { fontSize: 14 + 'px' }, text: '(', value: null, order: 3 },
    { style: { fontSize: 14 + 'px' }, text: ')', value: null, order: 4 },
    { style: { fontSize: 14 + 'px' }, text: '%', value: null, order: 5 },
    { style: {}, text: 'CE', value: 'CE', order: 6 },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '7',
        value: '7',
        order: 10,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '8',
        value: '8',
        order: 11,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '9',
        value: '9',
        order: 12,
    },
    {
        style: { fontWeight: 400, fontSize: 18 + 'px' },
        text: '÷',
        value: '/',
        order: 13,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '4',
        value: '4',
        order: 17,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '5',
        value: '5',
        order: 18,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '6',
        value: '6',
        order: 19,
    },
    {
        style: { fontWeight: 400, fontSize: 18 + 'px' },
        text: '×',
        value: '*',
        order: 20,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '1',
        value: '1',
        order: 24,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '2',
        value: '2',
        order: 25,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '3',
        value: '3',
        order: 26,
    },
    {
        style: { fontSize: 18 + 'px' },
        text: '−',
        value: '-',
        order: 27,
    },
    {
        style: { fontSize: 14 + 'px', backgroundColor: '#f1f3f4' },
        text: '0',
        value: '0',
        order: 31,
    },
    {
        style: {
            fontWeight: 700,
            backgroundColor: '#f1f3f4',
            fontSize: 18 + 'px',
        },
        text: '.',
        value: '.',
        order: 32,
    },
    {
        style: {
            fontWeight: 700,
            fontSize: 18 + 'px',
            color: '#ffffff',
            backgroundColor: '#4285f4',
        },
        text: '=',
        value: '=',
        order: 33,
    },
    {
        style: { fontWeight: 400, fontSize: 18 + 'px' },
        text: '+',
        value: '+',
        order: 34,
    },
];
